version: '2.1'

networks:
  network_front:
    external: true
  back:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/24

services:
  knx01:
    image: henfri/knxd:v0.12.6
    hostname: knx01
    restart: always
    extra_hosts:
      - knxgateway:192.168.2.22
    command: knxd --error=9 -e 0.0.77 -E 12.0.1:250 -D -T -R -S -c -i --send-delay=60 -b ipt:knxgateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      back:
        ipv4_address: 172.29.1.120
      network_front:
        ipv4_address: 192.168.2.120

  prometheus01:
    user: root
    image: prom/prometheus
    restart: always
    hostname: prometheus01
    depends_on:
      - knxpushgateway01
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/prometheus/config:/etc/prometheus
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      back:
        ipv4_address: 172.29.1.122
      network_front:
        ipv4_address: 192.168.2.122

  knxpushgateway01:
    image: prom/pushgateway
    restart: always
    hostname: knxpushgateway01
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      back:
        ipv4_address: 172.29.1.123
      network_front:
        ipv4_address: 192.168.2.123

  grafana01:
    user: root
    image: grafana/grafana
    depends_on:
      - prometheus01
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: always
    hostname: grafana01
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/grafana:/var/lib/grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    networks:
      back:
        ipv4_address: 172.29.1.124
      network_front:
        ipv4_address: 192.168.2.124

  knxexporter01:
    image: ubuntu
    restart: always
    hostname: knxexporter01
    depends_on:
      - knxpushgateway01
      - knx01
    environment:
      - "KNX_PUSH_DEBUG=false"
      - "KNX_PUSH_EXPORT=true"
      - "KNX_PUSH_DEP_INSTALL=true"
      - "KNX_PUSH_GATEWAY_HOST=knx01"
      - "KNX_PUSH_KNXTOOL_PATH=/knx/bin/knxtool"
      - "KNX_PUSH_PUSHGATEWAY_HOST=knxpushgateway01"
      - "KNX_PUSH_PUSHGATEWAY_PORT=9091"
      - "KNX_PUSH_PROMETHEUS_JOB=knxpushgateway"
      - "KNX_PUSH_CONFIGFILE=/knx/config/knx.csv"
      - "KNX_PUSH_UNCONFIGURED=false"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/knxexporter:/knx
      - ./data/knxexporter/lib/libeibclient.so.0:/lib/libeibclient.so.0
      - ./data/knxexporter/lib/libev.so.4:/lib/libev.so.4
    working_dir: /knx
    command: /bin/bash -c "/knx/knxpush.sh"
    networks:
      back:
        ipv4_address: 172.29.1.125
      network_front:
        ipv4_address: 192.168.2.125
