{
 "title": "Outdoor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature outdoor",
   "type": "gauge",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_15\",job=\"knxpushgateway\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Windspeed ",
   "type": "gauge",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_14\",job=\"knxpushgateway\"}",
     "legendFormat": "Windspeed"
    }
   ]
  },
  {
   "title": "Brightness outdoor",
   "type": "bargauge",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_10\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness east"
    },
    {
     "expr": "knx_state{groupaddress=\"0_0_11\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness south"
    },
    {
     "expr": "knx_state{groupaddress=\"0_0_12\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness west"
    }
   ]
  },
  {
   "title": "Temperature outdoor",
   "type": "graph",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_15\",job=\"knxpushgateway\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Windspeed outdoor",
   "type": "graph",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "velocityms", "label": "Windspeed" }
   ],
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_14\",job=\"knxpushgateway\"}",
     "legendFormat": "Windspeed"
    }
   ]
  },
  {
   "title": "Brightness outdoor",
   "type": "graph",
   "description": "Weather station",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lux", "label": "Brightness" }
   ],
   "targets": [
    {
     "expr": "knx_state{groupaddress=\"0_0_10\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness east"
    },
    {
     "expr": "knx_state{groupaddress=\"0_0_11\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness south"
    },
    {
     "expr": "knx_state{groupaddress=\"0_0_12\",job=\"knxpushgateway\"}",
     "legendFormat": "Brightness west"
    }
   ]
  }
 ]
}